//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBOAddonDeliveries.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \r\n ROW_NUMBER() OVER (Order by \"DocEntry\" desc) AS \"#\",\r\n\'N\' as \"Select\",\r" +
            "\n\"DocEntry\",\r\n\"CardCode\",\r\n\"CardName\",\r\n\"DocDueDate\",\r\n\"DocTotal\"\r\nFrom \r\n\"ORDR\"" +
            " \r\nWhere \"CardCode\" like \'%param%\'\r\nAnd \"DocStatus\" = \'O\'")]
        public string querySalesOrders {
            get {
                return ((string)(this["querySalesOrders"]));
            }
            set {
                this["querySalesOrders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select 
 ROW_NUMBER() OVER (Order by T0.""DocEntry"" desc) AS ""#"",
T0.""DocEntry"",
T0.""CardCode"",
T1.""ItemCode"",
T1.""WhsCode"",
T1.""Quantity"",
T1.""Price"",
T1.""LineNum"" as ""BaseLine""
From 
""ORDR"" T0
inner join ""RDR1"" T1 on T0.""DocEntry"" = T1.""DocEntry""
Where T0.""DocEntry"" in (param)
And T0.""DocStatus"" = 'O'")]
        public string querySalesOrderDetails {
            get {
                return ((string)(this["querySalesOrderDetails"]));
            }
            set {
                this["querySalesOrderDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT * FROM(
SELECT
ROW_NUMBER() OVER (Order by T0.""WhsCode"" desc) AS ""#"",
T1.""ItemCode"",
T1.""ItemName"",
T0.""WhsCode"",
T0.""OnHand"",
T0.""IsCommited"",
T0.""OnOrder"",
(T0.""OnHand""- T0.""IsCommited"") as ""IsAvaible""
FROM
OITW T0
INNER JOIN OITM T1 ON T0.""ItemCode"" = T1.""ItemCode""
WHERE T1.""ItemCode"" = 'param') XX
Order by XX.""#""")]
        public string queryItemByWarehouses {
            get {
                return ((string)(this["queryItemByWarehouses"]));
            }
            set {
                this["queryItemByWarehouses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \"CardCode\", \"CardName\" from \r\nOCRD\r\nWhere \"CardCode\" = \"param\"")]
        public string queryCustomerData {
            get {
                return ((string)(this["queryCustomerData"]));
            }
            set {
                this["queryCustomerData"] = value;
            }
        }
    }
}
